### PR TITLE
Handle missing semicolon in lemma rule

### PR DESCRIPTION
**Pull request by jowagner**
In my experiments training on `conllu` output of other parsers I encountered the error below, which means udpipe-future learned a lemma rule missing the semicolon separating casing and rule. This patch sets the lemma to be identical to the token in this situation.

```
Traceback (most recent call last):
  File "/path/UDPipe-Future/ud_parser.py", line 541, in <module>
    dev_accuracy, metrics = network.evaluate("dev", dev, dev_conllu, args)
  File "/path/UDPipe-Future/ud_parser.py", line 335, in evaluate
    conllu = self.predict(dataset, True, args)
  File "/path/UDPipe-Future/ud_parser.py", line 327, in predict
    dataset.write_sentence(conllu, sentences, overrides)
  File "/path/UDPipe-Future/ud_dataset.py", line 365, in write_sentence
    field = _apply_lemma_rule(fields[-1], field)
  File "/path/UDPipe-Future/ud_dataset.py", line 53, in _apply_lemma_rule
    casing, rule = lemma_rule.split(";", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

### CODE REVIEW

**Comment by foxik** [comment]
This shouldn't really happen -- all rules generated by `_gen_lemma_rule` contain a `;`, so the only cause I can think of is that either `<pad>`, `<unk>` or `<root>` is predicted (which will never happen after several batches of training).

Would you be so kind and printed the offending value, i.e., `lemma_rule` which caused it? If it is only `<pad>`, `<unk>` or `<root>`, I would prefer to have an exception only for these (and probably print some message to stderr). Thanks.

**Comment by jowagner** [comment]
I re-ran with the same data and initialisation seed 4 times on the same type of gpu card (rtx 2080 ti) and 2 times on a different type of gpu card (tesla K40) but couldn't reproduce the error (I got a gpu out of memory error instead each time). (I cannot easily get the exact same gpu card as this was observed in a cluster job.)

I now have a print statement to log the lemma rule and form should this happen again. However, as I found a token with 10037 bytes in the training data, the error probably is related to very long tokens and for my future training jobs I decided to remove training sentences that contain very long tokens. If the super long token was the cause we won't see the error again.

**Comment by foxik** [comment]
Thanks for the report... Maybe something will come up later :-)

**Comment by jowagner** [comment]
I ran more tests on multiple cluster nodes without success. The initially reported error occurred during dev set evaluation after the 9th epoch. However, with the current gpu drivers, I get out of memory errors before the first epoch finishes. Reducing model size (`--parser_deprel_dim 48`, `--cle_dim 12`, `--we_dim 96` and `--rnn_cell_dim 32`), I can avoid the memory errors but in 60 repetitions (30 with the same seed as in October and 30 new seeds) I did not get the lemma error again.

I changed this PR to throw an exception displaying the problematic lemma rule, not interfering with current behaviour (throwing a less informative default exception).

**Comment by foxik** [comment]
Great, merging.

**Pull request merged**
