### PR TITLE
catch empty lemma case rules

### PR DESCRIPTION
**Pull request by jowagner**
Skip lemma casing rules that are too short to contain both a upper/lowercase marker and an integer offset. I got such a rule, more specifically an empty rule, with
* default settings
* after the test score for epoch 20 is printed,
* a training file that is the concatenation of a bootstrap sample of en_lines-ud-train.conllu and predictions made on a subset of en_ewt-ud-train.conllu using a model trained on a different  bootstrap sample of en_lines-ud-train.conllu (co-training / tri-training; an extension of self-training), and
* a test file that is just a symlink to the training file.

I'm not sure skipping the rule is the right thing to do but at least it allows training to finish.

### CODE REVIEW

**Comment by jowagner** [comment]
Changing the numpy seed (PR #8 ), the error occurs after a different epoch. An alternative workaround may therefore be to discard to current epoch, shuffle the training data and try again.

**Comment by jowagner** [comment]
Looking at it again, one should also prepare for bad offsets. Let me know if you prefer a try except block around the next two lines instead.

**Comment by foxik** [comment]
I expect the rule to be the one generated by `_gen_lemma_rule`, I am not guarding against really malformed rules. Looking into the code, if a gold lemma is empty, the casing rule might be empty, which seems to be the situation you describe. So I am going to ignore an empty rule, and hopefully the situation will be resolved.

**Comment by jowagner** [comment]
Yes, there is an empty lemma in the training data I used:
```
$ fgrep $'\t' <~/d*/ud*v2.3/UD_Eng*LinES/*train*conllu | cut -f-3 | grep -E $'\t_$' -C 3
8       exotic  exotic
9       bediener        bediener
10      ,       ,
11      all     _
12      but     but
13      bodyless        bodyless
14      .       .
```

**Pull request closed without merging**
